camunda:
  bpm:
    admin-user:
      id: ${CAMUNDA_BPM_ADMIN_USER:admin}
      password: ${CAMUNDA_BPM_ADMIN_PASSWORD:DiasCosta@!!2025}
      firstName: Admin
      lastName: System
      email: admin@localhost
    run:
      auth:
        enabled: true
        authentication: basic
