global:
  scrape_interval: 30s
  evaluation_interval: 30s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'camunda-jmx'
    static_configs:
      - targets: ['camunda_camunda:9404']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  - job_name: 'camunda-workers'
    static_configs:
      - targets: 
        - 'camunda_worker-validation:8001'
        - 'camunda_worker-processing:8002'
        - 'camunda_worker-publication:8003'
        - 'camunda_worker-notification:8004'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s